### ISSUE TITLE
Failed to resolve gradle issue

### ISSUE THREAD

**Issue by anoop4real** [ar-android/AndroidSvgLoader#2]
Getting error

Error:(36, 13) Failed to resolve: com.github.ar-android:AndroidSvgLoader:1.0.0

**Comment by ar-android** [comment]
please upgrade to version 1.0.2

```gradle
implementation 'com.github.ar-android:AndroidSvgLoader:1.0.1'
```

Don't forget to add to your root build gradle.
```gradle
allprojects {
  repositories {
   maven { url 'https://jitpack.io' }
  }
 }
```

**Comment by anoop4real** [comment]
Awesome man, works cool

**Comment by linseyglr** [comment]
Getting error:
Failed to resolve: com.github.ar-android:AndroidSvgLoader:1.0.2
