### ISSUE TITLE
Crash if i use glide and svgloader 

### ISSUE THREAD

**Issue by androidlover5842** [ar-android/AndroidSvgLoader#6]
java.lang.NoSuchMethodError: No static method buildStreamModelLoader(Ljava/lang/Class;Landroid/content/Context;)Lcom/bumptech/glide/load/model/ModelLoader; in class Lcom/bumptech/glide/Glide; or its super classes (declaration of 'com.bumptech.glide.Glide' appears in /data/app/com.androidlover.uniteservices-wxNg3WgEg1HHqLtg5cHe8A==/base.apk)

**Comment by cliffgr** [comment]
Because this lib is using as his dependencies the glide

**Comment by androidlover5842** [comment]
wow too early reply

**Comment by uniquelipu** [comment]
Using implementation("com.github.bumptech.glide:glide:3.8.0") will resolve the issue
